In [10]:
import numpy as np

a = np.array([1,2,3])
b = np.array([4,5,6])

print(a)
print(type(a))

print(a.shape)
print(a.dtype)

a + b
a * b
a.mean()
a.std()

np.dot(a,b)

print(a*b)

[1 2 3]
<class 'numpy.ndarray'>
(3,)
int64
[ 4 10 18]


In [11]:
# Benchmark It, loop
import numpy as np
import time

a = np.array([1,2,3])
b = np.array([4,5,6])

size = 1_000_000

a = np.random.rand(size)
b = np.random.rand(size)

# NumPy
start = time.time()
np.dot(a, b)
print("NumPy:", time.time() - start)

# Python loop
a_list = a.tolist()
b_list = b.tolist()

start = time.time()
sum(x*y for x,y in zip(a_list, b_list))
print("Python:", time.time() - start)

# NumPy: 0.005675077438354492
# Python: 0.063812255859375

NumPy: 0.005675077438354492
Python: 0.063812255859375


In [14]:
# Matrix Operations (ML Core)
import numpy as np
A = np.array([[1,2,3],
              [4,5,6]])

B = np.array([[7,8],
              [9,10],
              [11,12]])

# np.dot(A, B)
# print(A @ B)


print(A.T) # Transpose

[[1 4]
 [2 5]
 [3 6]]


In [16]:
# Random Data (Used in ML)
X = np.random.rand(100, 3)
y = np.random.rand(100)

# print(X)
print(y)

[0.07882664 0.32133561 0.67610742 0.90329942 0.68448151 0.26513842
 0.913382   0.70277322 0.43056133 0.42080952 0.06571792 0.12613043
 0.03316965 0.18196533 0.55069713 0.7547016  0.82360602 0.69736292
 0.30225101 0.84784003 0.27710549 0.18501026 0.17795415 0.78092422
 0.98142456 0.69966722 0.22847809 0.2408678  0.5868305  0.31902393
 0.90809327 0.08220064 0.58219255 0.09637515 0.27999495 0.36467746
 0.36434619 0.48558622 0.32498655 0.89725017 0.23208768 0.4767795
 0.15512274 0.2873169  0.30139844 0.25073926 0.20475461 0.50190708
 0.09392917 0.12861401 0.20700221 0.3459513  0.61017408 0.33087555
 0.28793976 0.92780301 0.82160547 0.39948766 0.45250611 0.86398281
 0.22461426 0.49473886 0.10187318 0.97087115 0.89620902 0.4700944
 0.86320889 0.07968569 0.16107449 0.96338256 0.85172969 0.44505435
 0.402734   0.27385952 0.55380484 0.88006091 0.03269562 0.28838113
 0.87669861 0.67451979 0.88829853 0.05700591 0.69043613 0.83290486
 0.40025165 0.08969824 0.61161716 0.994493   0.94565708 0.194103

In [17]:
import numpy as np

a = np.array([1,2,3])
b = np.array([4,5,6])

print(np.dot(a,b))
print((a*b).sum())

32
32
